# Generated by Django 3.2.3 on 2023-09-05 12:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0004_auto_20230829_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'default_related_name': 'recipes',
                     'ordering': ('created',), 'verbose_name': 'Рецепт',
                     'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True,
                                       default=django.utils.timezone.now,
                                       verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
