# Generated by Django 3.2.3 on 2023-09-06 11:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_auto_20230906_1129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopingCartRecipe',
            new_name='ShoppingCartRecipe',
        ),
    ]
