# Generated by Django 3.2.3 on 2023-09-13 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0010_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriterecipe',
            options={'verbose_name': 'Любимый рецепт',
                     'verbose_name_plural': 'Любимые рецепты'},
        ),
        migrations.AlterModelOptions(
            name='followauthor',
            options={'verbose_name': 'Подписчик автора',
                     'verbose_name_plural': 'Подписчики авторов'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcartrecipe',
            options={'verbose_name': 'Рецепт в корзине',
                     'verbose_name_plural': 'Рецепты в корзине'},
        ),
    ]
